version: "3.9"

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: "hotel_parser"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
  back:
    build: .
    restart: always
    platform: linux/amd64
    ports:
      - "8800:8800"
  front:
    build:
      context: .
      dockerfile: ./front/Dockerfile
    ports:
      - "80:80"
    environment:
      NODE_ENV: production